name: CI
'on':
- push
- pull_request
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    # env:
    #   PATH: $HOME/.local/bin
    # container:
    #   image: ghcr.io/catthehacker/ubuntu:full-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # pip install --user localstack-client awscli
        # echo "$HOME/.local/bin" >> $GITHUB_PATH
    # - name: Install dependencies
    #   run: |
    #     set -eux
    #     python -m pip install --upgrade pip
    #     mkdir -p "$HOME/.local/bin" "$HOME/.local/lib"
    #     python -m pip install pytest boto3 requests awscli
    #     python -m pip install --user localstack-client
    #     python -m pip show localstack-client || true
    #     ls -la "$HOME/.local/bin" || true
    #     echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
    #     export PATH="$HOME/.local/bin:$PATH"
    #     echo "After export, which awslocal:"
    #     command -v awslocal || true

    # - name: Debug awslocal
    #   run: |
    #     echo "HOME=$HOME"
    #     echo "PATH=$PATH"
    #     echo "Contents of ~/.local/bin:"
    #     ls -la $HOME/.local/bin || true
    #     echo "Which awslocal:"
    #     which awslocal || true
    #     awslocal --version || true

    # - name: Set up LocalStack
    #   uses: localstack/setup-localstack@v0.2.4
    #   with:
    #     localstack-version: latest
    #     services: s3,lambda

    - name: Start LocalStack
      run: docker compose -f localstack/docker-compose.yml up -d
    - name: Wait for LocalStack to be ready
      run: sleep 30
    - name: Deploy LocalStack resources
      run: python localstack/localstack.py
    - name: Run tests
      run: PYTHONPATH=. pytest test/
    - name: Tear down LocalStack
      if: always()
      run: docker compose -f localstack/docker-compose.yml down
