name: CI
'on':
- push
- pull_request
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
        - 4566:4566
        options: --health-cmd "curl -s http://localhost:4566/health | grep 'UP'"--health-interval=5s
          --health-timeout=2s --health-retries=5
        env:
          SERVICES: s3,lambda
          DEBUG: '1'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install pytest boto3 localstack-client
    - name: Start LocalStack
      run: docker compose -f localstack/docker-compose.yml up -d && until curl -s
        http://localhost:4566/health | grep 'UP'; do sleep 2; done
    - name: Deploy LocalStack resources
      run: python localstack/localstack.py
    - name: Run tests
      run: PYTHONPATH=. pytest test/
