name: CI
'on':
- push
- pull_request
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install pytest boto3 localstack-client
    - name: Set up LocalStack
      uses: localstack/localstack@v3
      with:
        localstack-version: latest
        services: s3,lambda
    - name: Deploy LocalStack resources
      run: python localstack/localstack.py
    - name: Run tests
      run: PYTHONPATH=. pytest test/
    - name: Tear down LocalStack
      if: always()
      run: docker compose -f localstack/docker-compose.yml down
